package network.quant.api;

public enum SCFunctionType {
    CONSTRUCTOR_WITH_NO_PARAMETERS,
    CONSTRUCTOR_WITH_PARAMETERS,
    FUNCTION_CALL_WITH_NO_PARAMETERS,
    FUNCTION_CALL_WITH_PARAMETERS
}
